// deploy/Jenkinsfile
pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        choice(
            name: 'environment',
            choices: ['dev', 'staging', 'prod'],
            description: 'Select deployment environment'
        )

        string(
            name: 'branch',
            defaultValue: 'main',
            description: 'Branch to build'
        )
    }

    stages {
        stage('Initial Cleanup') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Prepare Laravel Dependencies') {
            steps {
                dir('laravel-app') {
                    sh '''
                        php -v
                        #composer install
                        cp .env.example .env
                        php artisan key:generate
                        php artisan migrate
                    '''
                }
            }
        }

        stage('Execute Laravel Tests') {
            steps {
                dir('laravel-app') {
                    sh '''
                        sed -i "s/^APP_KEY=.*/APP_KEY=$(php artisan key:generate --show)/" .env
                        mkdir -p storage/framework/{sessions,cache,views}
                        echo "APP_KEY Updated"
                        echo "Running Tests"
                        ./vendor/bin/phpunit --log-junit tests/junit.xml
                    '''
                }
            }
            post {
                always {
                    dir('laravel-app') {
                        junit 'tests/junit.xml'
                    }
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh """
                    ansible-playbook -i inventory/${params.environment}/hosts deploy/playbooks/site.yml
                """
            }
        }
    }
}
